Repository everyonewaiter/everyonewaiter-store-desktop, pull requests merged in 2025-09, with the labels that each got.

#1 chore: tailwindcss v4.1 적용
  electron.vite.config.ts
  package.json
  pnpm-lock.yaml
  src/renderer/src/assets/base.css
  src/renderer/src/assets/fonts/Pretendard-Bold.woff2
  src/renderer/src/assets/fonts/Pretendard-Medium.woff2
  src/renderer/src/assets/fonts/Pretendard-Regular.woff2
  src/renderer/src/assets/fonts/Pretendard-SemiBold.woff2
  tsconfig.json
Labels: chore

#2 feat: 공통 컴포넌트 및 설정 구현
  .prettierrc
  electron.vite.config.ts
  eslint.config.mjs
  package.json
  pnpm-lock.yaml
  src/main/index.ts
  src/renderer/src/App.tsx
  src/renderer/src/assets/base.css
  src/renderer/src/assets/electron.svg
  src/renderer/src/assets/icons/chevron-down.svg
  src/renderer/src/assets/icons/info.svg
  src/renderer/src/assets/main.css
  src/renderer/src/assets/wavy-lines.svg
  src/renderer/src/components/Button.tsx
  src/renderer/src/components/Checkbox.tsx
  src/renderer/src/components/Dropdown.tsx
  src/renderer/src/components/Form.tsx
  src/renderer/src/components/Input.tsx
  src/renderer/src/components/Label.tsx
  src/renderer/src/components/Spinner.tsx
  src/renderer/src/components/Versions.tsx
  src/renderer/src/main.tsx
  src/renderer/src/utils/cn.ts
  src/renderer/src/vite-env.d.ts
Labels: :necktie: feature

#3 refactor: import 경로 별칭 사용
  .vscode/settings.json
  package.json
  pnpm-lock.yaml
  src/main/index.ts
  src/preload/index.d.ts
  src/preload/index.ts
  src/renderer/src/components/Button.tsx
  src/renderer/src/components/Checkbox.tsx
  src/renderer/src/components/Dropdown.tsx
  src/renderer/src/components/Form.tsx
  src/renderer/src/components/Input.tsx
  src/renderer/src/components/Label.tsx
  src/renderer/src/main.tsx
Labels: :recycle: refactor

#5 feat: 기기 등록 페이지 퍼블리싱
  .github/PULL_REQUEST_TEMPLATE.md
  .prettierrc
  .vscode/settings.json
  electron.vite.config.ts
  eslint.config.mjs
  package.json
  pnpm-lock.yaml
  src/main/index.ts
  src/preload/index.d.ts
  src/preload/index.ts
  src/renderer/src/App.tsx
  src/renderer/src/assets/base.css
  src/renderer/src/assets/electron.svg
  src/renderer/src/assets/icons/chevron-down.svg
  src/renderer/src/assets/icons/index.ts
  src/renderer/src/assets/icons/info.svg
  src/renderer/src/assets/logos/index.ts
  src/renderer/src/assets/logos/logo-squared.svg
  src/renderer/src/assets/logos/logo.svg
  src/renderer/src/assets/logos/text.svg
  src/renderer/src/assets/main.css
  src/renderer/src/assets/wavy-lines.svg
  src/renderer/src/components/Button/Button.styles.ts
  src/renderer/src/components/Button/Button.tsx
  src/renderer/src/components/Button/Button.types.ts
  src/renderer/src/components/Button/ResponsiveButton.tsx
  src/renderer/src/components/Button/SimpleButton.tsx
  src/renderer/src/components/Checkbox.tsx
  src/renderer/src/components/Dropdown.tsx
  src/renderer/src/components/Input.tsx
  src/renderer/src/components/Label.tsx
  src/renderer/src/components/Spinner.tsx
  src/renderer/src/components/Versions.tsx
  src/renderer/src/components/index.ts
  src/renderer/src/constants/device.ts
  src/renderer/src/constants/index.ts
  src/renderer/src/constants/ui.ts
  src/renderer/src/main.tsx
  src/renderer/src/pages/device/DeviceLayout.tsx
  src/renderer/src/pages/device/DevicePage.tsx
  src/renderer/src/pages/device/DeviceStep1Comp.tsx
  src/renderer/src/pages/device/DeviceStep2Comp.tsx
  src/renderer/src/types/index.ts
  src/renderer/src/types/ui.ts
  src/renderer/src/utils/cn.ts
  src/renderer/src/utils/index.ts
  src/renderer/src/utils/type.ts
  src/renderer/src/vite-env.d.ts
Labels: :necktie: feature
